name: Buf CI
on: [push, pull_request]
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Passage en v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      # Vérifie le style (Lint)
      - uses: bufbuild/buf-lint-action@v1

      # Vérifie la rétrocompatibilité (Breaking changes)
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/${{ github.repository }}.git#branch=main'